sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]
        sonata_admin_doctrine_phpcr.tree_block:
            settings:
                id: '/cms'
            contexts:   [admin]
    blocks_by_class:
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\RssBlock:
            cache: cmf.block.cache.js_async

sonata_admin:
    extensions:
        cmf_sonata_phpcr_admin_integration.core.extension.child:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\Model\ChildInterface
        cmf_sonata_phpcr_admin_integration.core.extension.publish_workflow.time_period:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishTimePeriodInterface
        cmf_sonata_phpcr_admin_integration.core.extension.publish_workflow.publishable:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishableInterface
        cmf_sonata_phpcr_admin_integration.menu.extension.menu_node_referrers:
            implements:
                - Symfony\Cmf\Bundle\MenuBundle\Model\MenuNodeReferrersInterface
        cmf_sonata_phpcr_admin_integration.menu.extension.menu_options:
            implements:
                - Symfony\Cmf\Bundle\MenuBundle\Model\MenuOptionsInterface
        cmf_sonata_phpcr_admin_integration.routing.extension.route_referrers:
            implements:
                - Symfony\Cmf\Component\Routing\RouteReferrersInterface
        cmf_sonata_phpcr_admin_integration.routing.extension.frontend_link:
            implements:
                - Symfony\Cmf\Component\Routing\RouteReferrersReadInterface
            extends:
                - Symfony\Component\Routing\Route
        cmf_sonata_phpcr_admin_integration.seo.extension.metadata:
            implements:
                - Symfony\Cmf\Bundle\SeoBundle\SeoAwareInterface

    templates:
        layout:     admin/custom_layout.html.twig
        user_block: admin/user_block.html.twig
    dashboard:
        blocks:
            - { position: right, type: sonata.admin.block.admin_list }
            - { position: left, type: sonata_admin_doctrine_phpcr.tree_block }
        groups:
            content:
                label: Content
                icon: '<i class="fa fa-file-text-o"></i>'
                items:
                    - cmf_sonata_phpcr_admin_integration.content.admin
                    - cmf_sonata_phpcr_admin_integration.block.simple_admin
                    - cmf_sonata_phpcr_admin_integration.block.container_admin
                    - cmf_sonata_phpcr_admin_integration.block.reference_admin
                    - cmf_sonata_phpcr_admin_integration.block.action_admin
            routing:
                label: URLs
                icon: '<i class="fa fa-link"></i>'
                items:
                    - cmf_sonata_phpcr_admin_integration.routing.route_admin
                    - cmf_sonata_phpcr_admin_integration.routing.redirect_route_admin
            menu:
                label: Menu
                icon: '<i class="fa  fa-bars"></i>'
                items:
                    - cmf_sonata_phpcr_admin_integration.menu.menu_admin
                    - cmf_sonata_phpcr_admin_integration.menu.node_admin

sonata_doctrine_phpcr_admin:
    templates:
        form:
            - admin/form_admin_fields.html.twig
    document_tree:
        routing_defaults: [locale]

sonata_translation:
    locales: '%locales%'
    default_locale: '%locale%'
    phpcr: true

sonata_seo:
    page:
        title: CMF Sandbox
        metas:
            name:
                keywords: 'CMF, Symfony, Routing, Content, PHPCR'
