imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale: %locale%
    session:
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        coffee:
           bin: %coffee.bin%
           node: %coffee.node%
           apply_to: "\.coffee$"
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

# cmf configuration
doctrine_phpcr:
    # configure the PHPCR session
    #session:
    #    backend:
    #        type: doctrinedbal
    #        connection: doctrine.dbal.default_connection
    #    workspace: %phpcr_workspace%
    session:
        backend:
            url: %phpcr_url%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_pass%
    # enable the ODM layer
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%
        locales:
            en:
                - en
                - de
                - fr
            de:
                - de
                - en
                - fr
            fr:
                - fr
                - en
                - de


symfony_cmf_content: ~

symfony_cmf_chain_routing:
    chain:
        routers_by_id:
            symfony_cmf_chain_routing.doctrine_router: 20
            router.default: 100
    doctrine:
        enabled: true
        controllers_by_alias:
            demo_alias: sandbox_main.controller:aliasAction
        controllers_by_class:
            Sandbox\MainBundle\Document\DemoClassContent: sandbox_main.controller:classAction
            Symfony\Cmf\Bundle\ChainRoutingBundle\Document\RedirectRoute:  symfony_cmf_chain_routing.redirect_controller:redirectAction
        templates_by_class:
            Sandbox\MainBundle\Document\EditableStaticContent: SandboxMainBundle:EditableStaticContent:index.html.twig

knp_menu:
    twig: true

liip_vie:
    phpcr_odm: true
    map:
        'sioc:Post': 'Sandbox\MainBundle\Document\EditableStaticContent'
    use_coffee: %liip_vie.use_coffee%

sonata_admin:
    templates:
        # default global templates
        layout:  SandboxAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        dashboard: SandboxAdminBundle::dashboard.html.twig

fos_js_routing:
    routes_to_expose:
        - admin_sandbox_main_editablestaticcontent_create
        - admin_sandbox_main_editablestaticcontent_delete
        - admin_sandbox_main_editablestaticcontent_edit
        - admin_bundle_menu_menuitem_create
        - admin_bundle_menu_menuitem_delete
        - admin_bundle_menu_menuitem_edit
        - admin_bundle_multilangcontent_multilangmenuitem_create
        - admin_bundle_multilangcontent_multilangmenuitem_delete
        - admin_bundle_multilangcontent_multilangmenuitem_edit
        - admin_bundle_multilangcontent_multilangstaticcontent_create
        - admin_bundle_multilangcontent_multilangstaticcontent_delete
        - admin_bundle_multilangcontent_multilangstaticcontent_edit
        - admin_bundle_multilangcontent_multilanglanguageselectroute_create
        - admin_bundle_multilangcontent_multilanglanguageselectroute_delete
        - admin_bundle_multilangcontent_multilanglanguageselectroute_edit
        - admin_bundle_chainrouting_route_create
        - admin_bundle_chainrouting_route_delete
        - admin_bundle_chainrouting_route_edit
        - symfony_cmf_phpcr_browser_children

fos_rest:
    view:
        view_response_listener: false
