imports:
    - { resource: parameters.yml }
    - { resource: phpcr.yml }
    - { resource: security.yml }
    - { resource: @SymfonyCmfBlogBundle/Resources/config/routing/autoroute_default.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # bundles: [ ] # if enabled, every bundle must be added
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        coffee:
           bin: %coffee.bin%
           node: %coffee.node%
           apply_to: %coffee.extension%
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# for jackalope-doctrine-dbal
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        path:     %database_path%
        charset:  UTF8

# cmf configuration
doctrine_phpcr:
    # configure the PHPCR session
    session:
        backend: %phpcr_backend%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_pass%
    # enable the ODM layer
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%
        locales:
            en:
                - en
                - de
                - fr
            de:
                - de
                - en
                - fr
            fr:
                - fr
                - en
                - de

symfony_cmf_routing_extra:
    route_basepath: /cms/routes
    chain:
        routers_by_id:
            symfony_cmf_routing_extra.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        controllers_by_type:
            demo_type: sandbox_main.controller:typeAction
        controllers_by_class:
            Sandbox\MainBundle\Document\DemoClassContent: sandbox_main.controller:classAction
            Symfony\Cmf\Bundle\RoutingExtraBundle\Document\RedirectRoute:  symfony_cmf_routing_extra.redirect_controller:redirectAction
            Symfony\Cmf\Bundle\BlogBundle\Document\Blog: symfony_cmf_blog.blog_controller:listAction
            Symfony\Cmf\Bundle\BlogBundle\Document\Post: symfony_cmf_blog.blog_controller:viewPostAction

        templates_by_class:
            Symfony\Cmf\Bundle\ContentBundle\Document\MultilangStaticContent: SandboxMainBundle:MultilangStaticContent:index.html.twig

        locales: %locales%

symfony_cmf_simple_cms:
    routing:
        templates_by_class:
            Symfony\Cmf\Bundle\SimpleCmsBundle\Document\Page:  SymfonyCmfSimpleCmsBundle:Page:index.html.twig

knp_menu:
    twig: true

symfony_cmf_create:
    phpcr_odm: true
    map:
        'http://rdfs.org/sioc/ns#Post': 'Symfony\Cmf\Bundle\ContentBundle\Document\MultilangStaticContent'
    image:
        model_class: Symfony\Cmf\Bundle\CreateBundle\Document\Image
        controller_class: Symfony\Cmf\Bundle\CreateBundle\Controller\PHPCRImageController

symfony_cmf_content:
    multilang:
      locales: %locales%

symfony_cmf_menu:
    multilang:
      locales: %locales%

symfony_cmf_blog:
    blog_basepath: /cms/content


sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata_admin_doctrine_phpcr.tree_block:
            settings:
                id: '/cms'
            contexts:   [admin]
        symfony_cmf.block.action:
            cache: symfony_cmf.block.cache.js_async

sonata_admin:
    templates:
        # default global templates
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        user_block: SandboxMainBundle:Admin:user_block.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            - { position: right, type: sonata.admin.block.admin_list }
            - { position: left, type: sonata_admin_doctrine_phpcr.tree_block }
        groups:
            content:
                label: page content
                items:
                    - symfony_cmf_content.multilang.admin
                    - symfony_cmf_block.simple_admin
                    - symfony_cmf_block.container_admin
                    - symfony_cmf_block.reference_admin
                    - symfony_cmf_block.action_admin
            routing:
                label: page routes
                items:
                    - symfony_cmf_routing_extra.route_admin
                    - symfony_cmf_routing_extra.redirect_route_admin
            menu:
                label: menu structure
                items:
                    - symfony_cmf_menu.admin
                    - symfony_cmf_menu.multilang.admin
            blog:
                label: blog
                items:
                    - symfony_cmf_blog.admin
                    - symfony_cmf_post.admin
            simplecms:
                label: simple cms (content/routing/menu as one)
                items:
                    - symfony_cmf_simple_cms.admin.page

sonata_doctrine_phpcr_admin:
    document_tree_defaults: [locale]
    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - all
        Symfony\Cmf\Bundle\ContentBundle\Document\MultilangStaticContent:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Document\SimpleBlock
                - Symfony\Cmf\Bundle\BlockBundle\Document\ContainerBlock
                - Symfony\Cmf\Bundle\BlockBundle\Document\ReferenceBlock
                - Symfony\Cmf\Bundle\BlockBundle\Document\ActionBlock
        Symfony\Cmf\Bundle\BlockBundle\Document\ReferenceBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Document\ActionBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Document\SimpleBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Document\ContainerBlock:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Document\SimpleBlock
                - Symfony\Cmf\Bundle\BlockBundle\Document\ContainerBlock
                - Symfony\Cmf\Bundle\BlockBundle\Document\ReferenceBlock
                - Symfony\Cmf\Bundle\BlockBundle\Document\ActionBlock
        Symfony\Cmf\Bundle\SimpleCmsBundle\Document\Page: ~
        Symfony\Cmf\Bundle\RoutingExtraBundle\Document\Route:
            valid_children:
                - Symfony\Cmf\Bundle\RoutingExtraBundle\Document\Route
                - Symfony\Cmf\Bundle\RoutingExtraBundle\Document\RedirectRoute
        Symfony\Cmf\Bundle\RoutingExtraBundle\Document\RedirectRoute:
            valid_children: []
        Symfony\Cmf\Bundle\MenuBundle\Document\MenuNode:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Document\MenuNode
                - Symfony\Cmf\Bundle\MenuBundle\Document\MultilangMenuNode
        Symfony\Cmf\Bundle\MenuBundle\Document\MultilangMenuNode:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Document\MenuNode
                - Symfony\Cmf\Bundle\MenuBundle\Document\MultilangMenuNode
        Symfony\Cmf\Bundle\BlogBundle\Document\Blog:
            valid_children:
                - Symfony\Cmf\Bundle\BlogBundle\Document\Post
        Symfony\Cmf\Bundle\BlogBundle\Document\Post:
            valid_children: []

fos_js_routing:
    routes_to_expose:
        - admin_bundle_menu_menunode_*
        - admin_bundle_menu_multilangmenunode_*
        - admin_bundle_content_multilangstaticcontent_*
        - admin_bundle_block_simpleblock_*
        - admin_bundle_block_containerblock_*
        - admin_bundle_block_referenceblock_*
        - admin_bundle_block_actionblock_*
        - admin_bundle_blog_blog_*
        - admin_bundle_blog_post_*
        - symfony_cmf_routing_extra_route_admin_*
        - admin_bundle_simplecms_page_*
        - symfony_cmf_tree_browser.phpcr_children
        - symfony_cmf_tree_browser.phpcr_move
        - sonata.admin.doctrine_phpcr.phpcrodm_children
        - sonata.admin.doctrine_phpcr.phpcrodm_move

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters: true }

liip_search:
    restrict_by_language: true;

symfony_cmf_search:
    translation_strategy: child
#    translation_strategy: attribute
#    search_path: /cms/simple
    search_fields:
        title: title
        summary: body

lunetics_locale:
    strict_mode: true
    guessing_order:
        - cookie
        - router
        - browser
    allowed_locales: %locales%

# jackalope doctrine caching
#liip_doctrine_cache:
#    namespaces:
#        meta:
#            type: file_system
#        nodes:
#            type: file_system
