imports:
    - { resource: parameters.yml }
    - { resource: phpcr.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          '%secret%'
    router:          { resource: '%kernel.root_dir%/config/routing.yml' }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  '%locale%'
    session:
        name: symfony-cmf
    trusted_proxies: ~

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    form_themes:
        - '@CmfTreeBrowser/Form/fields.html.twig'

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    # bundles: [ ] # if enabled, every bundle must be added
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        coffee:
           bin:  '%coffee.bin%'
           node: '%coffee.node%'
           apply_to: '%coffee.extension%'
        # closure:
        #     jar: '%kernel.root_dir%/java/compiler.jar'
        # yui_css:
        #     jar: '%kernel.root_dir%/java/yuicompressor-2.4.2.jar'

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool:     { type: memory }

# for jackalope-doctrine-dbal
doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        path:     '%database_path%'
        charset:  UTF8

# cmf configuration
doctrine_phpcr:
    # configure the PHPCR session
    session:
        backend:   '%phpcr_backend%'
        workspace: '%phpcr_workspace%'
        username:  '%phpcr_user%'
        password:  '%phpcr_pass%'
    # enable the ODM layer
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: '%kernel.debug%'
        locales:
            en: [de, fr]
            de: [en, fr]
            fr: [en, de]

knp_menu:
    twig: true

cmf_core:
    multilang:
        locales: '%locales%'
    persistence:
        phpcr:
            enabled: true

cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        route_collection_limit: 10
        controllers_by_type:
            demo_type: app.content_controller:typeAction
        controllers_by_class:
            AppBundle\Document\DemoClassContent: app.content_controller:classAction
            Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute:  cmf_routing.redirect_controller:redirectAction

        templates_by_class:
            Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent: static_content/index.html.twig

cmf_seo:
    title: 'CMF Sandbox - %%content_title%%'
    description: 'The Content Management Framework. %%content_description%%'
    alternate_locale: ~

cmf_menu:
    voters:
        content_identity: ~

cmf_resource:
    description:
        enhancers: [sonata_phpcr_admin, cmf_tree_icons, doctrine_phpcr_position]
    repositories:
        default:
            type: doctrine/phpcr-odm

cmf_tree_browser:
    icons:
        AppBundle\Document\DemoSeoContent: 'fa fa-file-text-o'
        Sonata\BlockBundle\Model\BlockInterface: 'fa fa-cube'
        Symfony\Cmf\Bundle\SeoBundle\Model\SeoMetadata: 'fa fa-search'
        Symfony\Cmf\Bundle\MenuBundle\Model\MenuNode: 'fa fa-share-square-o'
        Symfony\Cmf\Bundle\RoutingBundle\Model\Route: 'fa fa-link'
        Symfony\Cmf\Bundle\RoutingBundle\Model\RedirectRoute: 'fa fa-reply'

cmf_sonata_phpcr_admin_integration:
    bundles:
        seo: ~
        menu: ~
        core: ~
        content:
           ivory_ckeditor:
              config_name: cmf_sonata_phpcr_admin_integration
        block:
            basepath: /cms/content
            menu_basepath: /cms/content
        routing: ~

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]
        sonata_admin_doctrine_phpcr.tree_block:
            settings:
                id: '/cms'
            contexts:   [admin]
    blocks_by_class:
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\RssBlock:
            cache: cmf.block.cache.js_async

sonata_admin:
    extensions:
        cmf_sonata_phpcr_admin_integration.core.extension.child:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\Model\ChildInterface
        cmf_sonata_phpcr_admin_integration.core.extension.publish_workflow.time_period:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishTimePeriodInterface
        cmf_sonata_phpcr_admin_integration.core.extension.publish_workflow.publishable:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishableInterface
        cmf_sonata_phpcr_admin_integration.menu.extension.menu_node_referrers:
            implements:
                - Symfony\Cmf\Bundle\MenuBundle\Model\MenuNodeReferrersInterface
        cmf_sonata_phpcr_admin_integration.menu.extension.menu_options:
            implements:
                - Symfony\Cmf\Bundle\MenuBundle\Model\MenuOptionsInterface
        cmf_sonata_phpcr_admin_integration.routing.extension.route_referrers:
            implements:
                - Symfony\Cmf\Component\Routing\RouteReferrersInterface
        cmf_sonata_phpcr_admin_integration.routing.extension.frontend_link:
            implements:
                - Symfony\Cmf\Component\Routing\RouteReferrersReadInterface
            extends:
                - Symfony\Component\Routing\Route
        cmf_sonata_phpcr_admin_integration.seo.extension.metadata:
            implements:
                - Symfony\Cmf\Bundle\SeoBundle\SeoAwareInterface

    templates:
        layout:     admin/custom_layout.html.twig
        user_block: admin/user_block.html.twig
    dashboard:
        blocks:
            - { position: right, type: sonata.admin.block.admin_list }
            - { position: left, type: sonata_admin_doctrine_phpcr.tree_block }
        groups:
            content:
                label: Content
                icon: '<i class="fa fa-file-text-o"></i>'
                items:
                    - cmf_sonata_phpcr_admin_integration.content.admin
                    - cmf_sonata_phpcr_admin_integration.block.simple_admin
                    - cmf_sonata_phpcr_admin_integration.block.container_admin
                    - cmf_sonata_phpcr_admin_integration.block.reference_admin
                    - cmf_sonata_phpcr_admin_integration.block.action_admin
            routing:
                label: URLs
                icon: '<i class="fa fa-link"></i>'
                items:
                    - cmf_sonata_phpcr_admin_integration.routing.route_admin
                    - cmf_sonata_phpcr_admin_integration.routing.redirect_route_admin
            menu:
                label: Menu
                icon: '<i class="fa  fa-bars"></i>'
                items:
                    - cmf_sonata_phpcr_admin_integration.menu.menu_admin
                    - cmf_sonata_phpcr_admin_integration.menu.node_admin

sonata_doctrine_phpcr_admin:
    templates:
        form:
            - admin/form_admin_fields.html.twig
    document_tree:
        routing_defaults: [locale]

sonata_translation:
    locales: '%locales%'
    default_locale: '%locale%'
    phpcr: true

sonata_seo:
    page:
        title: CMF Sandbox
        metas:
            name:
                keywords: 'CMF, Symfony, Routing, Content, PHPCR'

ivory_ck_editor:
    configs:
        cmf_sonata_phpcr_admin_integration: { toolbar: standard }

sensio_framework_extra:
    router:  { annotations: true }
    request: { converters: true }

lunetics_locale:
    strict_mode: true
    guessing_order:
        - router
        - cookie
        - browser
    allowed_locales: '%locales%'

doctrine_cache:
    providers:
        phpcr_meta:
            type: file_system
        phpcr_nodes:
            type: file_system

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            CmfContentBundle:
                namespace_prefix: 'Symfony\Cmf\Bundle\ContentBundle'
                path: '@AppBundle/Resources/config/serializer/cmf'

fos_rest:
    view:
        force_redirects:
            html: true
        formats:
            json: true
            xml: true
        templating_formats:
            html: true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    format_listener:
        rules:
            - { path: ^/, priorities: [ html, json, xml, css ], fallback_format: html, prefer_extension: false }
