imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        coffee:
           bin: %coffee.bin%
           node: %coffee.node%
           apply_to: "\.coffee$"
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
# doctrine:
#     dbal:
#         driver:   %database_driver%
#         host:     %database_host%
#         port:     %database_port%
#         dbname:   %database_name%
#         user:     %database_user%
#         password: %database_password%
#         charset:  UTF8
#
#     orm:
#         auto_generate_proxy_classes: %kernel.debug%
#         auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# cmf configuration
doctrine_phpcr:
    # configure the PHPCR session
    session:
        backend:
            url: %phpcr_url%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_pass%
    # enable the ODM layer
    odm:
        auto_mapping: true

symfony_cmf_navigation:
    controllers_by_alias:
        static_pages: sandbox_main.controller:indexAction
        editablestatic: sandbox_main.controller:indexAction

symfony_cmf_chain_routing:
    chain:
        routers_by_id:
            # TODO: enable doctrine router once its working
            #symfony_cmf_chain_routing.doctrine_router: 200
            router.default: 100
    doctrine:
        controllers_by_alias:
            static_pages: sandbox_main.controller:indexAction
            editablestatic: sandbox_main.controller:indexAction

knp_menu:
    twig: true

liip_vie:
    phpcr_odm: true
    #orm: doctrine.orm.my_entity_manager
    map:
        '<http://rdfs.org/sioc/ns#Post>': 'Sandbox\MainBundle\Document\EditableStaticContent'
    use_coffee: %liip_vie.use_coffee%
