services:
    app.content_controller:
        class: AppBundle\Controller\ContentController
        parent: cmf_content.controller

    app.exception_listener:
        class: AppBundle\EventListener\SandboxExceptionListener
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: kernel.event_subscriber }

    app.twig.menu_extension:
        class: AppBundle\Twig\MenuExtension
        arguments: ['@knp_menu.helper', '@knp_menu.matcher']
        tags:
            - { name: twig.extension }

    app.resource_voter:
        class: AppBundle\Security\ResourceVoter
        tags:
            - { name: security.voter }
